steps:
  # Step 1: Build the Docker image
  - name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cts01-shreyashree/my-repo/demo-app:$BUILD_ID'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'us-central1-docker.pkg.dev/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/cts01-shreyashree/my-repo/demo-app:$BUILD_ID'

images:
  # Specify the image built and pushed to Artifact Registry
  - 'us-central1-docker.pkg.dev/cts01-shreyashree/my-repo/demo-app:$BUILD_ID'
